"""empty message

Revision ID: 442ccf84df52
Revises: 90f6620121c9
Create Date: 2024-07-26 19:13:46.309215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442ccf84df52'
down_revision = '90f6620121c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['uid'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
